services:
  app:
    container_name: vanijay_seller
    image: ghcr.io/mis-takely/vanijay-seller:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000" # Expose to localhost port 3001, for host Nginx to proxy
    env_file: .env

networks:
  default:
    external: true
    name: vanijay-network
